name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: format
        run: pnpm run format

      - name: lint
        run: pnpm run lint

      - name: typecheck
        run: pnpm run typecheck

      - name: build
        run: pnpm run build
