name: E2E

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Deploy
    types:
      - completed
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: e2e

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Start app container
        run: docker compose -f e2e.yaml up --build -d
        working-directory: .

      - if: ${{ github.event_name != 'workflow_dispatch' }}
        run: docker compose -f e2e.yaml ps -a
        working-directory: .

      - if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Run E2E
        run: pnpm run test

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Run E2E
        run: pnpm run test:production

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: e2e/test-results
          retention-days: 7
