name: Lighthouse
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["deploy"]
    types:
      - completed

jobs:
  lighthouse-check:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          urls: "https://apple-yagi.me,https://apple-yagi.me/timeline"

      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "100"
          minBestPracticesScore: "100"
          minPerformanceScore: "95"
          minSeoScore: "100"

      - if: failure()
        run: echo failure
